// Generated by CoffeeScript 2.0.0-beta2
(function() {
  'use strict';
  var CND, GRAMMAR, NEARLEY, PATH, badge, debug, echo, help, info, log, parser, rpr, urge, warn, whisper;

  PATH = require('path');

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'NEARLEY-EXAMPLES';

  log = CND.get_logger('plain', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  NEARLEY = require('nearley');

  GRAMMAR = require('./grammars/json');

  parser = new NEARLEY.Parser(GRAMMAR.ParserRules, GRAMMAR.ParserStart);

  parser.feed('[1,2]');

  info(parser.results);

}).call(this);
